@startuml
":Tabuleiro" as Tabuleiro -> Tabuleiro : AcharVencedor(vencedores : Jogador)
Activate Tabuleiro  
loop for each jogador in vencedores
    loop for each propriedade in jogador.propriedades
    activate Tabuleiro
    Tabuleiro -> ": Jogador" as Jogador : Receber(Propriedade.GetPreco())
        activate Jogador
        Jogador -> ": Propriedade" as Propriedade : GetPreco()
       activate Propriedade
       Jogador <<-- Propriedade : preco : int
       deactivate Propriedade
       deactivate Jogador
    end loop
end loop
Tabuleiro -> Jogador : valorFinal = vencedores[0].GetSaldo
activate Jogador
Tabuleiro <<-- Jogador : saldo : int
deactivate Jogador
loop for each jogador in vencedores
Tabuleiro -> Jogador : GetSaldo()
activate Jogador
Tabuleiro <-- Jogador : saldo
deactivate Jogador
opt saldo >= valorFinal
    Tabuleiro -> Tabuleiro : vencedor = jogador
deactivate Tabuleiro
end opt
end loop
@enduml