@startuml comunicacao

": Tabuleiro" as Tab -> ": Jogador" as Jog : IniciarRodada()
activate Jog

opt efeitoPrisao
    Jog -> ": efeitoPrisao" as Pris : RealizarEfeito()
end

opt efeitoEspecialPersonagem
    Jog -> ": efeitoEspecialPersonagem" as EFS : RelizarEfeito()
end 

Jog -> Jog : JogarDado() : int
    activate Jog
    Jog -> ": InterfaceUsuario" as GUI : AnimarDado(resultado : int)
        activate GUI
        deactivate GUI
    deactivate Jog

Jog -> Jog : Mover(passos : int)
    activate Jog
    Jog -> Tab: getCasas() : Casa[ ]
        activate Tab
        Tab -->> Jog
        deactivate Tab
    loop passos > passos
        Jog -> Jog : posicao ++
        activate Jog
        deactivate Jog
        Jog -> GUI : MoverPersonagemUmPasso(personagem, posicao)
        activate GUI
        deactivate GUI
        opt posicao = 0
         Jog -> Jog : GanharDinheiroPorVolta()
         activate Jog
            Jog -> GUI : AtualizarSaldo(personagem, saldo)
            activate GUI
            deactivate GUI 
         deactivate Jog
        end opt
    end loop
    
    Jog -> "casas[posicao] : Casa" as Casa : RealizarEfeitos()
        activate Casa
        deactivate Casa
    deactivate Jog


Jog ->> Tab : ProximoJogador()
deactivate Jog

@enduml