@startuml 

": InterfaceUsuario" as GUI <- "propriedade : Propriedade" as Prp : PerguntarComprarPropriedade(propriedade:Propriedade, Comprar(jogadorAtual:Jogador) )
    activate GUI
    activate Prp
        opt Comprar() 
            GUI -> Prp : Comprar(comprador:jogador)
            deactivate GUI
                activate Prp
                    Prp ->> "compador : Jogador" as Jog : Pagar(preco:int)
                    activate Jog
                    deactivate Jog

                    Prp -> Prp : SetProprietario (comprador:Jogador)
                    activate Prp

                    loop for each comprador.propriedades[]
                        Prp -> "PropriedadeMesmaCor: Propriedade" as Prp2: GetCor()
                        activate Prp2
                        Prp2 -->> Prp
                        deactivate Prp2

                        alt PropriedadeMesmaCor.cor == propriedade.cor
                            Prp -> Prp : AluguelDobrado = True
                            activate Prp
                            deactivate Prp
                            Prp -> Prp2 : AluguelDobrado = True
                            activate Prp2
                            deactivate Prp2  
                        end
                    deactivate Prp
                    end

                Prp ->> Jog : propriedades[].add (propriedade : Propriedade)
                    activate Jog
                    deactivate Jog
                    Prp ->> GUI : AdicionarPropriedade (comprador.getPersonagem(), propriedade:Propriedade)
                    activate GUI
                    deactivate GUI
                deactivate Prp
            deactivate Prp

        end ComprarPropriedade

@enduml