@startuml
Activate Tabuleiro
":Tabuleiro" as Tabuleiro -> Tabuleiro : AcabarJogo()

Create ": Jogador" as Jogador
    Tabuleiro -> Jogador : <<create>> vencedores [ ]
    Tabuleiro -> Tabuleiro : MaiorSaldo() : int
    activate Tabuleiro
    deactivate Tabuleiro   
    loop for each jogador in jogadores   
        Tabuleiro -> Jogador : GetSaldo()
        activate Jogador
        Tabuleiro <<-- Jogador: saldo
        deactivate Jogador
        opt saldo == maiorSaldo
            Tabuleiro -> Tabuleiro : vencedores.add(jogador)
            activate Tabuleiro
            deactivate Tabuleiro
        end alt
    end loop

    alt vencedores.Count > 1
        Tabuleiro-> Tabuleiro: AcharVencedor(vencedores)
        activate Tabuleiro
        deactivate Tabuleiro

    else vencedores == 1
        Tabuleiro -> Tabuleiro: vencedor = vencedores[0]
        activate Tabuleiro
        deactivate Tabuleiro
    end
    Tabuleiro ->> ": InterfaceUsuario" as GUI : AcabarJogo(vencedor.GetPersonagem())
@enduml