@startuml diagrama
skinparam linetype ortho
skinparam classAttributeIconSize 0

entity Tabuleiro{
    + Casas : List<Casa>
    + Cartas : List<Carta>
    + Jogadores : List<Jogador>
    - static Instance : Tabuleiro

    + static GetInstance() : Tabuleiro
    + ProximoJogador() : void
    + JogadorAtual(): Jogador
}

entity Casa{
    - Nome: string
    - Posicao : int   
    - Efeito : Efeito
    + RealizarEfeitos() : void
}

entity Propriedade{
    - Preco: int
    - Aluguel: int
    - AluguelDobrado : bool
    + Cor: Cor
    - Proprietario: Jogador
    + ChecarProprietario(Jogador) : bool
    + CobrarAluguel(): int
    + Comprar(Jogador): void
}

entity Jogador{
    - Personagem: Personagem
    - Propriedades: List<Propriedade>
    - Saldo : int
    - Posicao: int
    + EfeitoInicial : Efeito
    + EfeitoHabeasCorpus : Efeito
    + Receber(int): void
    + Pagar(int): void
    + IniciarRodada() : void
    + Mover(int) : void
    + Teleportar(int) : void
    - JogarDado(): int
    - GanharDinheiroPorVolta(): void
}

enum Cor{
    AMARELO
    AZUL
    BRANCO
    LARANJA
    VERMELHO
    MARROM
    ROXO
}

enum Personagem{
    CACHORRO
    GATO
    BARCO
    CARRO
}

entity Carta{
    - Texto : string
    - Efeitos : List<Efeito>
    + RealizarEfeitos() : void
}

entity Efeito{
    + RealizarEfeito() : void
}

entity EfeitoEspecialPersonagem{
    - EfeitoComprarCarta : Efeito
    - Personagem : Personagem
    - EscolhePropriedade() : Propriedade
    - EntregarCartaAoPersonagem(Efeito) : void
}

entity EfeitoEscolhePropriedade{
    - Cor1, Cor2 : Cor
    - EscolhePropriedadeCor() : Propriedade
}

entity EfeitoPropriedadeGratis{
    - PegaOuPaga() : Propriedade
}

entity EfeitoTeleporte{
    - Destino : int
    - TeleportarJogador() : void
}

entity EfeitoPassos{
    - Passos : int
    - AndarJogador() : void
}

entity EfeitoComprarCarta{
    - ComprarCarta() : void 
}

entity EfeitoTransacao{
    - Transacao : int
    - AplicarTransacao() : void
}

entity EfeitoHabeasCorpus{
    - SairDaPrisao() : void
}

entity EfeitoMoverOuComprar{
    - EfeitoPassos : Efeito
    - EfeitoComprar : Efeito
    - EscolheMoverOuComprar() : Efeito
}

entity EfeitoVaParaPrisao{
    - EfeitoTeleporte : Efeito
    - EfeitoPrisao : Efeito
}

entity EfeitoPrisao{
    - VerificarHabeasCorpus() : bool
    - CobrarMulta() : void
}

Tabuleiro "1" *-- "*" Jogador
Tabuleiro "1" *-- "*" Casa

Casa --> Propriedade

Jogador "1"  *-- "*" Propriedade

Carta "*" *-- "*" Efeito
Casa "1" *-- "1" Efeito

Efeito --> EfeitoComprarCarta
Efeito --> EfeitoEscolhePropriedade
Efeito --> EfeitoEspecialPersonagem
Efeito --> EfeitoHabeasCorpus
Efeito --> EfeitoMoverOuComprar
Efeito --> EfeitoPassos
Efeito --> EfeitoPropriedadeGratis
Efeito --> EfeitoPrisao
Efeito --> EfeitoTeleporte
Efeito --> EfeitoTransacao
Efeito --> EfeitoVaParaPrisao

@enduml