@startuml diagrama
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam nodesep 100
skinparam ranksep 50

entity EfeitoComprarCarta{
    + RealizarEfeito() : void
    - ComprarCarta() : void 
}

entity EfeitoEscolherPassos{
    + RealizarEfeito() : void

    - EscolherPassos() : void
}

entity EfeitoEscolherPropriedade{
    - Cor1, Cor2 : Cor

    + RealizarEfeito() : void
    - EscolherPropriedadeCor() : Propriedade
}

entity EfeitoEspecialPersonagem{
    - EfeitoComprarCarta : EfeitoComprarCarta
    - Personagem : Personagem

    + RealizarEfeito() : void
    - EscolherPropriedade() : Propriedade
    - EntregarCartaAoPersonagem(Efeito) : void
}

entity EfeitoGO{
    - EfeitoTeleporte : EfeitoTeleporte
    - EfeitoTransacao : EfeitoTransacao 

    + RealizarEfeito() : void
    - SairDaPrisao() : void
}

entity EfeitoHabeasCorpus{
    + RealizarEfeito() : void
    - SairDaPrisao() : void
}

entity EfeitoMoverOuComprar{
    - EfeitoPassos : EfeitoPassos
    - EfeitoComprarCarta : EfeitoComprarCarta

    + RealizarEfeito() : void
    - EscolherMoverOuComprar() : Efeito
}

entity EfeitoPassos{
    - Passos : int

    + RealizarEfeito() : void
    - AndarJogador() : void
}

entity EfeitoPrisao{
    + RealizarEfeito() : void
    - VerificarHabeasCorpus() : bool
    - CobrarMulta() : void
}

entity EfeitoPropriedadeGratis{
    - IndicePropriedade : int

    + RealizarEfeito() : void
    - PegarOuPagar() : Propriedade
}

entity EfeitoTeleporte{
    - Destino : int

    + RealizarEfeito() : void
    - TeleportarJogador() : void
}

entity EfeitoTransacao{
    - Transacao : int

    + RealizarEfeito() : void
    - AplicarTransacao() : void
}

entity EfeitoVaParaPrisao{
    - MotivosParaPrisao : List<string>
    - EfeitoTeleporte : EfeitoTeleporte
    - EfeitoPrisao : EfeitoPrisao
    
    + RealizarEfeito() : void
}

@enduml