@startuml
": Propriedade" as Propriedade -> ": Tabuleiro" as Tabuleiro : GetInstance().JogadorAtual()
activate Propriedade
Propriedade <-- Tabuleiro : Jogador

opt aluguel dobrado
    Propriedade -> Propriedade: valorAPagar *= 2
end opt

Propriedade ->  " JogadorDaVez : Jogador" as Jogador1 : GetSaldo()
activate Jogador1
Propriedade <-- Jogador1 : saldo
deactivate Jogador1

alt saldo < valorAPagar
    Propriedade -> "Proprietario : Jogador" as Jogador2 : proprietário.Receber(saldo)
    activate Propriedade
    activate Jogador2
    deactivate Propriedade
    deactivate Jogador2
else
    Propriedade -> Jogador2 : proprietário.Receber(valorAPagar)
        activate Propriedade
    activate Jogador2
    deactivate Propriedade
    deactivate Jogador2
end alt

Propriedade -> Jogador1 : jogadorDaVez.Pagar(valorAPagar)
    activate Propriedade
    activate Jogador1
    deactivate Propriedade
    deactivate Jogador1
@enduml