@startuml diagrama
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam nodesep 200
skinparam ranksep 150

entity Carta{
    - Texto : string
    + RealizarEfeitos() : void
}

entity Casa{
    # Nome: string
    - Posicao : int
    - Efeito : Efeito

    + RealizarEfeitos() : void
}

enum Cor{
    AMARELO
    AZUL
    BRANCO
    LARANJA
    MARROM
    VERMELHO
    ROXO
}

interface Efeito{
    + RealizarEfeito() : void
}

entity Jogador{
    - Saldo : int
    - Posicao: int
    + EfeitoHabeasCorpus: EfeitoHabeasCorpus

    - JogarDado(): int
    - GanharDinheiroPorVolta(): void
    + Receber(int): void
    + Pagar(int): void
    + IniciarRodada() : void
    + Mover(int) : void
    + Teleportar(int) : void
}

enum Personagem{
    BARCO
    CACHORRO
    CARRO
    GATO
}

entity Propriedade{
    - Preco: int
    - Aluguel: int
    - AluguelDobrado : bool [= false]
    - Proprietario : Jogador [= null]

    + RealizarEfeitos() : void
    + ChecarProprietario(Jogador) : bool
    + RemoverProprietario(Jogador) : void
    + CobrarAluguel(): void
    + Comprar(Jogador): void
}

entity Tabuleiro<<singleton>>{
    <u>- Instance : Tabuleiro</u>
    - jogadorDaVez : int [=0]
    - cartaDaVez : int
    - acabou : bool

    <u>+ GetInstance() : Tabuleiro</u>
    - EmbaralharCartas() : Cartas[Carta]
    + InicializarJogadores(): void
    + ProximoJogador() : void
    + JogadorAtual() : Jogador
    + PegarCarta() : Carta
    + MaiorSaldo() : int
    + AcharVencedor(Vencedores[Jogador]) : Jogador
    + AcabarJogo() : void
}

Carta o- "*...*" Efeito : - Efeitos

Casa --> "1...1" Efeito : - Efeito

Jogador  o-- "1...*" Propriedade : + Propriedades
Jogador --> "1...1" Personagem : - Personagem
Jogador --> Efeito : + EfeitoInicial

Propriedade --|> Casa
Propriedade --> "1..1" Cor : + Cor
Propriedade --> Jogador: - Proprietario

Tabuleiro *- "1...*" Jogador : + Jogadores []
Tabuleiro *- "1...*" Casa : + Casas []
Tabuleiro *- "1...*" Carta : + Cartas []

@enduml