@startuml
opt (!Acabou)
Activate Tabuleiro
": Tabuleiro" as  Tabuleiro->": Tabuleiro" as  Tabuleiro : MudarVez(JogadorAtual().GetPersonagem(), false)
Tabuleiro -> ": InterfaceUsuario" as GUI : JogadorAtual().GetPersonagem()
    activate Tabuleiro
    activate GUI
    GUI -> ": Jogador" as Jogador : GetPersonagem()
    activate Jogador
    GUI <<-- Jogador : personagem
    deactivate Jogador
    Tabuleiro <<-- GUI : Jogador
    deactivate GUI
    deactivate Tabuleiro
Tabuleiro -> Tabuleiro : JogadorDaVez +=1
    opt jogadorDaVez >= Jogadores.count
        Tabuleiro -> Tabuleiro : JogadorDaVez = 0
    end
Tabuleiro -> Tabuleiro : MudarVez(JogadorAtual().GetPersonagem(), true)
    Tabuleiro -> GUI : JogadorAtual().GetPersonagem()
    activate Tabuleiro
    activate GUI
    GUI -> ": Jogador" as Jogador : GetPersonagem()
    activate Jogador
    GUI <<-- Jogador : Personagem
    deactivate Jogador
    Tabuleiro <<-- GUI : Jogador
    deactivate GUI
    deactivate Tabuleiro
Tabuleiro ->> Jogador : JogadorAtual().IniciarRodada()
deactivate Tabuleiro
end
@enduml