@startuml diagrama
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam nodesep 200
skinparam ranksep 150

entity Tabuleiro{
    <u>- Instance : Tabuleiro</u>

    <u>+ GetInstance() : Tabuleiro</u>
    + ProximoJogador() : void
    + JogadorAtual(): Jogador
}

entity Casa{
    - Nome: string
    - Posicao : int

    + RealizarEfeitos() : void
}

entity Propriedade{
    - Preco: int
    - Aluguel: int
    - AluguelDobrado : bool

    + RealizarEfeitos() : void
    + ChecarProprietario(Jogador) : bool
    + CobrarAluguel(): int
    + Comprar(Jogador): void
}

entity Jogador{
    - Saldo : int
    - Posicao: int
    + EfeitoHabeasCorpus: EfeitoHabeasCorpus

    - JogarDado(): int
    - GanharDinheiroPorVolta(): void
    + Receber(int): void
    + Pagar(int): void
    + IniciarRodada() : void
    + Mover(int) : void
    + Teleportar(int) : void
}

enum Cor{
    AMARELO
    AZUL
    BRANCO
    LARANJA
    VERMELHO
    MARROM
    ROXO
}

enum Personagem{
    CACHORRO
    GATO
    BARCO
    CARRO
}

entity Carta{
    - Texto : string
    + RealizarEfeitos() : void
}

interface Efeito{
    + RealizarEfeito() : void
}

Tabuleiro *- "1...*" Jogador : + Jogadores
Tabuleiro *- "1...*" Casa : + Casas
Tabuleiro *- "1...*" Carta : + Cartas

Casa --|> Propriedade
Casa --> "1...1" Efeito : - Efeito

Propriedade --> "1..1" Cor : + Cor
Propriedade --> Jogador: - Proprietario

Jogador  o-- "1...*" Propriedade : + Propriedades
Jogador --> "1...1" Personagem : - Personagem
Jogador --> Efeito : + EfeitoInicial

Carta o- "*...*" Efeito : - Efeitos

@enduml