@startuml diagrama
skinparam linetype ortho
skinparam classAttributeIconSize 0

entity Tabuleiro{
    - Propriedade : Propriedade[]
    - Prisao : Prisao
    + cartaSorte : CartaSorte
    - pontoDePartida : PontoDePartida
}

entity Propiedade{
    - Nome: string
    - Preco: int
    - Aluguel: int
    + cor: Cor
    - Proprietario: Jogador
    - Posicao : int   
}

entity Jogador{
    - id: int
    - Dado : int[]
    - Propriedades: Propriedade[]
    - Saldo : int
    - Posicao: int
}

enum Cor{
    AMARELO
    AZUL
    BRANCO
    LARANJA
    VERMELHO
    MARROM
    ROXO
}
enum CartaSorte{ 
        carta1
        carta2
        carta3
        carta4
        carta5
        carta6
        carta7
        carta8
        carta9
        carta10
        carta11
        carta12
        carta13
        carta14
        carta15
        carta16
        carta17
        carta18
        carta19
        carta20
}

entity Partida{
    - tabuleiro : Tabuleiro
    - jogadores: Jogador[]
    }

    Tabuleiro "1" *-- "*" Jogador
    Tabuleiro "1" *-- "*" Propriedade
    
    Jogador "1"  *-- "*" Propiedade

@enduml