@startuml comunicacao

skinparam linestyle ortho

rectangle "Tabuleiro" as one
Actor "Jogador" as two
rectangle "Casa" as three
rectangle "Efeito" as four
rectangle "Carta" as five

one -right- two: 1: IniciarRodada(): int --> \n 2.1.1.1: ProximoJogador(): void <--

two --> two: 2: JogarDado(): int \n 2.1: Mover(posicao: int): void
two --> three: 2.1.1: RealizarEfeitos(): void

three --> four: 3: RealizarEfeitos(): void
four --> five: 4: RealizarEfeitos(): void

@enduml