@startuml comunicacao

skinparam linestyle ortho

Actor "Jogador 1 : Jogador" as jogador
rectangle "Propriedade" as propriedade

jogador --> propriedade: 1: ChecarProprietario(jogador:Jogador): bool \n [Proprietario == null] 2A: Comprar(jogador:Jogador) \n [Proprietario != Jogador 1 && Proprietario != null] 2B: PagarAluguel()

@enduml