@startuml comunicacao

skinparam linestyle ortho

rectangle "Casa" as one
rectangle "Carta" as two
rectangle "EfeitoComprarCarta" as three
rectangle "EfeitoMoverComprar" as four
rectangle "EfeitoMover" as five

one -right- three: 1: RealizarEfeitos() ->

three -right- two: 1.1: ComprarCarta() ->

two --> four: 1.1.1: RealizarEfeitos()

four --> four: 1.1.2: EscolheMoverOuComprar(): Efeito
four --> five: 1.1.2.1A: RealizarEfeitos()
four --> three: 1.1.2.1B: RealizarEfeitos()

@enduml