@startuml
alt proprietario == null
 "propriedade : Propriedade" as Prp -> "jogadorAtual : Jogador" as Jog : GetSaldo() : int
activate Prp
activate Jog
deactivate Jog
    opt saldo >= preco
    Prp ->> ": InterfaceUsuario" as GUI : PerguntarComprarPropriedade(propriedade:Propriedade, Comprar(jogadorAtual:Jogador), null)
    activate GUI
    deactivate GUI
opt Jogador decide comprar 
    Prp -> Prp : Comprar(jogadorAtual:Jogador)
end Jogador decide comprar
    activate Prp
        
    end Saldo >= preco

else
        Prp -> Prp : ChecarProprietario(jogadorAtual):bool
        activate Prp
        deactivate Prp
            opt proprietario != jogadorAtual
            Prp -> Prp : CobrarAluguel()
            activate Prp
                alt aluguelDobrado == True
                 Prp -> Prp: valorAPagar = aluguel * 2
                else
                 Prp -> Prp: valorAPagar = aluguel
                end aluguelDobrado
                Prp -> Jog: GetSaldo():int
                activate Prp
                activate Jog
                Prp <<-- Jog
                deactivate Jog
                deactivate Prp

                alt saldo < valorAPagar               
                 Prp ->> "proprietario : Jogador" as Jog2: Receber(saldo:int)
                 activate Jog2
                 deactivate Jog2
                else
                 Prp ->> Jog2: Receber(valorAPagar:int)
                 activate Jog2
                 deactivate Jog2
            deactivate Prp
                end Saldo < valorAPagar
           
            Prp ->> Jog : Pagar(valorAPagar)
                activate Jog
                deactivate Jog
                deactivate Prp
            
            end


end proprietario == null
@enduml