@startuml
activate Tabuleiro

":Tabuleiro" as Tabuleiro -> Tabuleiro : InicializarJogadores()

Create ": Jogador" as Jogador
loop for each personagem in Personagem
        activate Tabuleiro
        Tabuleiro -> Jogador : <<create>> personagem, interfaceUsuario.GetNumeroPlayer(personagem)
            activate Jogador
            Jogador-> ": interfaceUsuario" as GUI : GetNumeroPlayer(personagem) 
            activate GUI
            Jogador <-- GUI : numeroPlayer : int
            deactivate GUI
        deactivate Jogador
    deactivate Tabuleiro   
end loop
Tabuleiro -> Tabuleiro : random(jogadores[ ])
@enduml