    - AndarJogador() : void
}

entity EfeitoComprarCarta{
    - ComprarCarta() : void 
}

entity EfeitoTransacao{
    - Transacao : int
    - AplicarTransacao() : void
}

entity EfeitoHabeasCorpus{
    - SairDaPrisao() : void
}

entity EfeitoMoverOuComprar{
    - EfeitoPassos : EfeitoPassos
    - EfeitoComprar : EfeitoComprar
    - EscolheMoverOuComprar() : Efeito
}

entity EfeitoVaParaPrisao{
    - EfeitoTeleporte : EfeitoTeleporte
    - EfeitoPrisao : EfeitoPrisao
}

entity EfeitoPrisao{
    - VerificarHabeasCorpus() : bool
    - CobrarMulta() : void
}

Tabuleiro *-- "1...*" Jogador : + Jogadores
Tabuleiro *-- "1...*" Casa : + Casas
Tabuleiro *-- "1...*" Carta : + Cartas

Casa --> Propriedade
Casa *-- "1...1" Efeito : - Efeito

Propriedade -left-> "1..1" Cor : + Cor
Propriedade -> Jogador: - Proprietario

Jogador  o-- "1...*" Propriedade : + Propriedades
Jogador --> "1...1" Personagem : - Personagem
Jogador -> Efeito : + EfeitoInicial
Jogador -> EfeitoHabeasCorpus: + EfeitoHabeasCorpus

Carta o-- "*...*" Efeito : - Efeitos

Efeito --> EfeitoComprarCarta
Efeito --> EfeitoEscolhePropriedade
Efeito --> EfeitoEspecialPersonagem
Efeito --> EfeitoHabeasCorpus
Efeito --> EfeitoMoverOuComprar
Efeito --> EfeitoPassos
Efeito --> EfeitoPropriedadeGratis
Efeito --> EfeitoPrisao
Efeito --> EfeitoTeleporte
Efeito --> EfeitoTransacao
Efeito --> EfeitoVaParaPrisao

@enduml