@startuml
opt (!Acabou)
Activate Tabuleiro
": Tabuleiro" as  Tabuleiro->": Tabuleiro" as  Tabuleiro : 1:MudarVez(JogadorAtual().GetPersonagem(), false)
Tabuleiro -> ": InterfaceUsuario" as GUI : 2: JogadorAtual().GetPersonagem()
    activate Tabuleiro
    activate GUI
    GUI -> ": Jogador" as Jogador : 3: GetPersonagem()
    activate Jogador
    GUI <<-- Jogador : personagem
    deactivate Jogador
    Tabuleiro <<-- GUI : Jogador
    deactivate GUI
    deactivate Tabuleiro
Tabuleiro -> Tabuleiro : 4: JogadorDaVez +=1
    opt jogadorDaVez >= Jogadores.count
        Tabuleiro -> Tabuleiro : 5: JogadorDaVez = 0
    end
Tabuleiro -> Tabuleiro : 6: MudarVez(JogadorAtual().GetPersonagem(), true)
    Tabuleiro -> GUI : 7: JogadorAtual().GetPersonagem()
    activate Tabuleiro
    activate GUI
    GUI -> ": Jogador" as Jogador : 8: GetPersonagem()
    activate Jogador
    GUI <<-- Jogador : personagem
    deactivate Jogador
    Tabuleiro <<-- GUI : Jogador
    deactivate GUI
    deactivate Tabuleiro
Tabuleiro ->> Jogador : 9: JogadorAtual().IniciarRodada()
deactivate Tabuleiro
end
@enduml